# Generated by Django 4.1 on 2022-09-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='deliverDate',
            field=models.DateTimeField(blank=True),
        ),
    ]
