# Generated by Django 4.1 on 2022-09-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveryDate',
            field=models.DateTimeField(null=True),
        ),
    ]
